name: Build and publish multiarch
on:
  push:
    branches:
      - master
      - "*-multiarch"
      - "multiarch*"
      - java8-openj9
      - java11*
      - java16*
      - test/*
    tags:
      - "[0-9]+.[0-9]+.[0-9]+"
      - "[0-9]+.[0-9]+.[0-9]+-multiarch*"
      - "[0-9]+.[0-9]+.[0-9]+-*multiarch"
      - "[0-9]+.[0-9]+.[0-9]+-java8-openj9"
      - "[0-9]+.[0-9]+.[0-9]+-java11*"
      - "[0-9]+.[0-9]+.[0-9]+-java16*"
    paths-ignore:
      - "*.md"
      - "docs/**"
      - "examples/**"

jobs:
  docker-buildx:
    if: github.repository == 'itzg/docker-minecraft-server'
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: |
            itzg/minecraft-server
          tags: |
            type=ref,event=branch
            type=ref,event=tag
          flavor: |
            latest=${{ github.event_name == 'push' && github.ref == 'refs/heads/master' }}

      - name: Setup Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Cache Docker layers
        uses: actions/cache@v2.1.6
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1.2.0

      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2.7.0
        with:
          context: .
          platforms: linux/amd64,linux/arm/v7,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          # ensure latest base image is used
          pull: true
          cache-from: type=local,src=/tmp/.buildx-cache
          cache-to: type=local,dest=/tmp/.buildx-cache-new
          labels: ${{ steps.meta.outputs.labels }}

      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}

      - # Temp fix
        # https://github.com/docker/build-push-action/issues/252
        # https://github.com/moby/buildkit/issues/1896
        name: Move cache
        run: |
          rm -rf /tmp/.buildx-cache
          mv /tmp/.buildx-cache-new /tmp/.buildx-cache